package report_test

import (
	"encoding/json"
	"fmt"

	"github.com/kalanas210/runmesh/internal/report"
)

// ExampleRender pins the shape of a report: an overview in sentences, then each
// step's plain values as a list, in step id order and field order.
func ExampleRender() {
	deps := map[string]json.RawMessage{
		"analyze": json.RawMessage(`{"busiest_month":"1960-07","months":144,"trend":"increasing"}`),
		"fetch":   json.RawMessage(`{"status":200,"bytes":2180}`),
	}
	r := report.Render(report.Options{Title: "Airline passengers"}, deps, "job_1", "report")
	fmt.Print(r.Markdown)
	// Output:
	// # Airline passengers
	//
	// _Generated by RunMesh job `job_1`, step `report`._
	//
	// ## Overview
	//
	// This report covers 2 steps: `analyze` and `fetch`. `analyze` returned 3 fields. `fetch` returned 2 fields.
	//
	// ## analyze
	//
	// - `busiest_month`: 1960-07
	// - `months`: 144
	// - `trend`: increasing
	//
	// ## fetch
	//
	// - `bytes`: 2180
	// - `status`: 200
}
