// Package report renders a Markdown document from a set of step results.
//
// It lives on its own because two things need it and they cannot share a tool
// implementation: the in-process registry entry (internal/tools.Report) and the
// task image's implementation of the same tool (cmd/task), which is what runs
// when the executor is Kubernetes.
//
// cmd/task otherwise imports nothing from this repository, on purpose — the
// container tool contract is environment in, marker line out, so that an image
// in any language is a first-class citizen, and the binary stays a few hundred
// kilobytes rather than linking client-go. This package does not weaken either
// argument: it is stdlib-only and a few hundred lines, and it is not the
// contract. What it prevents is the alternative, which is the same Markdown
// renderer written twice and drifting apart section by section until a plan
// produces a different report depending on where it ran.
//
// The document is written for a person. It opens with an overview in
// sentences, writes plain values as a list and passages of text as quotes, and
// keeps JSON for the one thing prose cannot carry honestly: nested structure.
// It is deliberately not written by a language model. This code runs inside a
// task pod, and a model would need an API key in the one place a key must never
// be; it would also make a report a different document on every run.
package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Options are the report tool's parameters.
type Options struct {
	Title   string `json:"title,omitempty"`
	Summary string `json:"summary,omitempty"`
	// Include narrows the report to these step ids, in this order. Empty means
	// every dependency, in id order — sorted rather than in map order, because
	// a report whose sections shuffle between runs is not a report.
	Include []string `json:"include,omitempty"`
	// Raw appends each step's full result as a JSON block. Off by default: the
	// sections are written for a reader, and the data itself is one flag away,
	// and on every step's own result.
	Raw bool `json:"raw,omitempty"`
}

// Validate checks what can be checked without the results.
func (o Options) Validate() error {
	seen := make(map[string]bool, len(o.Include))
	for _, id := range o.Include {
		if strings.TrimSpace(id) == "" {
			return fmt.Errorf("include contains an empty step id")
		}
		if seen[id] {
			return fmt.Errorf("include names %q twice", id)
		}
		seen[id] = true
	}
	return nil
}

// Result is what the tool returns.
type Result struct {
	Markdown string   `json:"markdown"`
	Bytes    int      `json:"bytes"`
	Sections int      `json:"sections"`
	Missing  []string `json:"missing,omitempty"`
}

const (
	// longText is where a string stops being a value and becomes a passage.
	// Past it, or at a line break, a string gets a quote of its own rather than
	// a list item that would have to cut it short.
	longText = 120
	// maxListedItems is the longest list written out item by item. A longer one
	// is data rather than prose, and stays JSON under a sentence saying how long
	// it is.
	maxListedItems = 20
)

// Render builds the document.
//
// deps is the results of the steps this one depends on, keyed by step id — the
// only channel through which data reaches a step. A report tool that fetched
// its own inputs would need a store handle, and tools do not get one.
func Render(o Options, deps map[string]json.RawMessage, jobID, stepID string) Result {
	order := o.Include
	if len(order) == 0 {
		order = make([]string, 0, len(deps))
		for id := range deps {
			order = append(order, id)
		}
		sort.Strings(order)
	}

	var present, missing []string
	for _, id := range order {
		if _, ok := deps[id]; !ok {
			// Named in `include` but absent from depends_on. Reported in the
			// document rather than failing the step: four sections of five,
			// with the fifth named, is more use than no report — and the plan
			// bug is still plainly visible.
			missing = append(missing, id)
			continue
		}
		present = append(present, id)
	}

	var md bytes.Buffer
	title := o.Title
	if title == "" {
		title = "Report"
	}
	fmt.Fprintf(&md, "# %s\n\n", title)
	if o.Summary != "" {
		fmt.Fprintf(&md, "%s\n\n", o.Summary)
	}
	fmt.Fprintf(&md, "_Generated by RunMesh job `%s`, step `%s`._\n\n", jobID, stepID)
	fmt.Fprintf(&md, "## Overview\n\n%s\n\n", overview(present, missing, deps))

	for _, id := range present {
		fmt.Fprintf(&md, "## %s\n\n", id)
		writeSection(&md, deps[id], o.Raw)
	}
	if len(missing) > 0 {
		fmt.Fprintf(&md, "## Missing\n\nNo result was available for: %s. "+
			"A step must be listed in depends_on for its result to reach this one.\n\n",
			strings.Join(missing, ", "))
	}

	return Result{
		Markdown: md.String(),
		Bytes:    md.Len(),
		Sections: len(present),
		Missing:  missing,
	}
}

// overview says in sentences what the report holds, so a reader knows what
// they are looking at before the first section — and a report shown as plain
// text, which is how the console shows it, still opens with prose.
func overview(present, missing []string, deps map[string]json.RawMessage) string {
	var b strings.Builder
	if len(present) == 0 {
		b.WriteString("No step results reached this report.")
	} else {
		ids := make([]string, len(present))
		for i, id := range present {
			ids[i] = code(id)
		}
		fmt.Fprintf(&b, "This report covers %s: %s.", count(len(present), "step", "steps"), joinList(ids))
		for _, id := range present {
			fmt.Fprintf(&b, " %s %s.", code(id), describe(deps[id]))
		}
	}
	if len(missing) > 0 {
		ids := make([]string, len(missing))
		for i, id := range missing {
			ids[i] = code(id)
		}
		fmt.Fprintf(&b, " No result was available for %s.", joinList(ids))
	}
	return strings.TrimSpace(b.String())
}

// describe names the shape of one result in a few words.
func describe(raw json.RawMessage) string {
	v, err := decode(raw)
	if err != nil {
		return "returned a result that is not valid JSON"
	}
	switch t := v.(type) {
	case nil:
		return "returned nothing"
	case map[string]any:
		if len(t) == 0 {
			return "returned an empty object"
		}
		return "returned " + count(len(t), "field", "fields")
	case []any:
		if len(t) == 0 {
			return "returned an empty list"
		}
		return "returned a list of " + count(len(t), "item", "items")
	case string:
		if strings.TrimSpace(t) == "" {
			return "returned empty text"
		}
		return "returned text"
	default:
		return "returned " + valueText(t)
	}
}

// writeSection renders one dependency's result for a reader.
//
// Whatever the shape of the data, the section says what it is before showing
// it. Nested structure is the one thing it does not turn into prose: flattening
// a second level would produce a document that lies about the data's shape, so
// that stays JSON, under a sentence saying what it is.
func writeSection(md *bytes.Buffer, raw json.RawMessage, appendRaw bool) {
	v, err := decode(raw)
	if err != nil {
		// Not JSON at all. Shown verbatim, because a guess at its shape would
		// be worse than the bytes.
		writeFenced(md, "", string(raw))
		return
	}

	shownWhole := false
	switch t := v.(type) {
	case nil:
		md.WriteString("The step returned nothing.\n\n")
	case string:
		writeText(md, t)
	case map[string]any:
		writeObject(md, t)
	case []any:
		shownWhole = writeList(md, t)
	default:
		fmt.Fprintf(md, "The step returned %s.\n\n", valueText(t))
	}

	if appendRaw && !shownWhole {
		md.WriteString("The full result:\n\n")
		writeFenced(md, "json", string(indentJSON(raw)))
	}
}

// writeObject writes an object's plain values as a list, then its passages of
// text as quotes, then its nested values, each under a heading of its own.
func writeObject(md *bytes.Buffer, obj map[string]any) {
	if len(obj) == 0 {
		md.WriteString("The step returned an empty object.\n\n")
		return
	}
	var passages, nested []string
	listed := false
	for _, k := range sortedKeys(obj) {
		v := obj[k]
		switch {
		case !isScalar(v):
			nested = append(nested, k)
		case isPassage(v):
			passages = append(passages, k)
		default:
			fmt.Fprintf(md, "- %s: %s\n", code(k), valueText(v))
			listed = true
		}
	}
	if listed {
		md.WriteString("\n")
	}
	for _, k := range passages {
		fmt.Fprintf(md, "### %s\n\n", code(k))
		writeText(md, obj[k].(string))
	}
	for _, k := range nested {
		fmt.Fprintf(md, "### %s\n\n", code(k))
		switch v := obj[k].(type) {
		case []any:
			writeList(md, v)
		case map[string]any:
			writeNestedObject(md, v)
		}
	}
}

// writeNestedObject writes a flat object as a list, and anything deeper as
// JSON.
func writeNestedObject(md *bytes.Buffer, obj map[string]any) {
	if len(obj) == 0 {
		md.WriteString("An empty object.\n\n")
		return
	}
	for _, v := range obj {
		if !isScalar(v) || isPassage(v) {
			fmt.Fprintf(md, "An object with %s:\n\n", count(len(obj), "field", "fields"))
			writeFenced(md, "json", marshalIndent(obj))
			return
		}
	}
	for _, k := range sortedKeys(obj) {
		fmt.Fprintf(md, "- %s: %s\n", code(k), valueText(obj[k]))
	}
	md.WriteString("\n")
}

// writeList writes a short list of plain values item by item. A long or nested
// list is data rather than prose, and stays JSON under a sentence saying how
// long it is. It reports whether the whole list went out as JSON.
func writeList(md *bytes.Buffer, list []any) bool {
	if len(list) == 0 {
		md.WriteString("An empty list.\n\n")
		return false
	}
	plain := len(list) <= maxListedItems
	for _, item := range list {
		if !isScalar(item) || isPassage(item) {
			plain = false
			break
		}
	}
	if !plain {
		fmt.Fprintf(md, "A list of %s:\n\n", count(len(list), "item", "items"))
		writeFenced(md, "json", marshalIndent(list))
		return true
	}
	for _, item := range list {
		fmt.Fprintf(md, "- %s\n", valueText(item))
	}
	md.WriteString("\n")
	return false
}

// writeText quotes a passage line by line.
//
// A quote is the one Markdown block a line of data cannot break out of. The
// text is a step's result, which in the general case is a fetched web page, and
// a line in it that reads "## Totals" stays inside the quote instead of
// becoming a heading of the report. Formatting hygiene rather than a security
// control: nothing renders this document as HTML.
func writeText(md *bytes.Buffer, s string) {
	s = strings.TrimRight(strings.ReplaceAll(s, "\r\n", "\n"), "\n")
	if strings.TrimSpace(s) == "" {
		md.WriteString("_(empty)_\n\n")
		return
	}
	for _, line := range strings.Split(s, "\n") {
		if line == "" {
			md.WriteString(">\n")
			continue
		}
		md.WriteString("> " + line + "\n")
	}
	md.WriteString("\n")
}

// writeFenced writes a code block whose fence is longer than any run of
// backticks in the content, so a result that contains ``` cannot end the block
// early.
func writeFenced(md *bytes.Buffer, lang, content string) {
	fence := strings.Repeat("`", max(3, longestRun(content, '`')+1))
	fmt.Fprintf(md, "%s%s\n%s\n%s\n\n", fence, lang, strings.TrimRight(content, "\n"), fence)
}

// decode parses a result, keeping numbers exactly as the tool wrote them.
func decode(raw json.RawMessage) (any, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var v any
	err := dec.Decode(&v)
	return v, err
}

func isScalar(v any) bool {
	switch v.(type) {
	case map[string]any, []any:
		return false
	}
	return true
}

func isPassage(v any) bool {
	s, ok := v.(string)
	return ok && (len(s) > longText || strings.ContainsAny(s, "\r\n"))
}

// valueText renders one plain value inside a sentence or a list item.
func valueText(v any) string {
	switch t := v.(type) {
	case nil:
		return "_(none)_"
	case string:
		if s := strings.Join(strings.Fields(t), " "); s != "" {
			return s
		}
		return "_(empty)_"
	case json.Number:
		return t.String()
	case bool:
		if t {
			return "true"
		}
		return "false"
	}
	return fmt.Sprint(v)
}

// code wraps s in an inline code span that s cannot close, whatever backticks
// it contains.
func code(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	fence := strings.Repeat("`", longestRun(s, '`')+1)
	if strings.HasPrefix(s, "`") || strings.HasSuffix(s, "`") {
		return fence + " " + s + " " + fence
	}
	return fence + s + fence
}

func count(n int, one, many string) string {
	if n == 1 {
		return "1 " + one
	}
	return fmt.Sprintf("%d %s", n, many)
}

// joinList joins items the way a sentence does: "a", "a and b", "a, b and c".
func joinList(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	}
	return strings.Join(items[:len(items)-1], ", ") + " and " + items[len(items)-1]
}

func longestRun(s string, c byte) int {
	best, run := 0, 0
	for i := 0; i < len(s); i++ {
		if s[i] != c {
			run = 0
			continue
		}
		run++
		best = max(best, run)
	}
	return best
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// marshalIndent re-encodes decoded data for a JSON block. HTML escaping is off:
// it would show a page's "<b>" as "\u003cb\u003e", which is a report misquoting
// its data.
func marshalIndent(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return fmt.Sprint(v)
	}
	return strings.TrimRight(buf.String(), "\n")
}

func indentJSON(v json.RawMessage) []byte {
	var buf bytes.Buffer
	if err := json.Indent(&buf, v, "", "  "); err != nil {
		return v
	}
	return buf.Bytes()
}
