// Package report renders a Markdown document from a set of step results.
//
// It lives on its own because two things need it and they cannot share a tool
// implementation: the in-process registry entry (internal/tools.Report) and the
// task image's implementation of the same tool (cmd/task), which is what runs
// when the executor is Kubernetes.
//
// cmd/task otherwise imports nothing from this repository, on purpose — the
// container tool contract is environment in, marker line out, so that an image
// in any language is a first-class citizen, and the binary stays a few hundred
// kilobytes rather than linking client-go. This package does not weaken either
// argument: it is stdlib-only and a few hundred lines, and it is not the
// contract. What it prevents is the alternative, which is the same Markdown
// renderer written twice and drifting apart section by section until a plan
// produces a different report depending on where it ran.
package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Options are the report tool's parameters.
type Options struct {
	Title   string `json:"title,omitempty"`
	Summary string `json:"summary,omitempty"`
	// Include narrows the report to these step ids, in this order. Empty means
	// every dependency, in id order — sorted rather than in map order, because
	// a report whose sections shuffle between runs is not a report.
	Include []string `json:"include,omitempty"`
	// Raw appends each section's result as a JSON block. A pointer so that
	// "absent" and "false" are distinguishable: the default is true, and the
	// data is what somebody debugging a plan actually needs.
	Raw *bool `json:"raw,omitempty"`
}

// Validate checks what can be checked without the results.
func (o Options) Validate() error {
	seen := make(map[string]bool, len(o.Include))
	for _, id := range o.Include {
		if strings.TrimSpace(id) == "" {
			return fmt.Errorf("include contains an empty step id")
		}
		if seen[id] {
			return fmt.Errorf("include names %q twice", id)
		}
		seen[id] = true
	}
	return nil
}

// Result is what the tool returns.
type Result struct {
	Markdown string   `json:"markdown"`
	Bytes    int      `json:"bytes"`
	Sections int      `json:"sections"`
	Missing  []string `json:"missing,omitempty"`
}

// Render builds the document.
//
// deps is the results of the steps this one depends on, keyed by step id — the
// only channel through which data reaches a step. A report tool that fetched
// its own inputs would need a store handle, and tools do not get one.
func Render(o Options, deps map[string]json.RawMessage, jobID, stepID string) Result {
	order := o.Include
	if len(order) == 0 {
		order = make([]string, 0, len(deps))
		for id := range deps {
			order = append(order, id)
		}
		sort.Strings(order)
	}

	raw := true
	if o.Raw != nil {
		raw = *o.Raw
	}

	var md bytes.Buffer
	title := o.Title
	if title == "" {
		title = "Report"
	}
	fmt.Fprintf(&md, "# %s\n\n", title)
	if o.Summary != "" {
		fmt.Fprintf(&md, "%s\n\n", o.Summary)
	}
	fmt.Fprintf(&md, "_Generated by RunMesh job `%s`, step `%s`._\n\n", jobID, stepID)

	var missing []string
	for _, id := range order {
		result, ok := deps[id]
		if !ok {
			// Named in `include` but absent from depends_on. Reported in the
			// document rather than failing the step: four sections of five,
			// with the fifth named, is more use than no report — and the plan
			// bug is still plainly visible.
			missing = append(missing, id)
			continue
		}
		fmt.Fprintf(&md, "## %s\n\n", id)
		writeSection(&md, result, raw)
	}
	if len(missing) > 0 {
		fmt.Fprintf(&md, "## Missing\n\nNo result was available for: %s. "+
			"A step must be listed in depends_on for its result to reach this one.\n\n",
			strings.Join(missing, ", "))
	}

	return Result{
		Markdown: md.String(),
		Bytes:    md.Len(),
		Sections: len(order) - len(missing),
		Missing:  missing,
	}
}

// writeSection renders one dependency's result.
//
// A flat object becomes a small table, because that is the shape of most tool
// results and a table is readable. Anything else falls back to a fenced JSON
// block. The fallback is not a failure case — it is the honest rendering of
// data whose shape belongs to whichever tool produced it, and guessing harder
// would produce a document that lies about nested structure.
func writeSection(md *bytes.Buffer, result json.RawMessage, raw bool) {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(result, &obj); err == nil && len(obj) > 0 {
		keys := make([]string, 0, len(obj))
		for k := range obj {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		md.WriteString("| field | value |\n|---|---|\n")
		for _, k := range keys {
			fmt.Fprintf(md, "| `%s` | %s |\n", k, cell(obj[k]))
		}
		md.WriteString("\n")
		if !raw {
			return
		}
	}

	md.WriteString("```json\n")
	md.Write(indentJSON(result))
	md.WriteString("\n```\n\n")
}

// cell renders one value for a Markdown table cell, escaped and bounded.
//
// Pipes and newlines both break a table, and a tool result is data from
// somewhere else — in the general case from a fetched web page, via a step a
// language model chose to add. This is formatting hygiene rather than a
// security control: nothing renders the output as HTML.
func cell(v json.RawMessage) string {
	s := strings.TrimSpace(string(v))
	var unquoted string
	if json.Unmarshal(v, &unquoted) == nil {
		s = unquoted
	}
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.Join(strings.Fields(s), " ")
	const max = 200
	if len(s) > max {
		s = s[:max] + "..."
	}
	if s == "" {
		return "_(empty)_"
	}
	return s
}

func indentJSON(v json.RawMessage) []byte {
	var buf bytes.Buffer
	if err := json.Indent(&buf, v, "", "  "); err != nil {
		return v
	}
	return buf.Bytes()
}
